apiVersion: v1
metadata:
  name: set-pid-limit-kubelet-two
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: KubeletConfig
    metadata:
      name: set-pid-limit-kubelet-two
    spec:
      kubeletConfig:
        podPidsLimit: 16384
kind: ConfigMap
