apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: heli-test
  namespace: clusters
spec:
  arch: amd64
  clusterName: heli-test
  management:
    autoRepair: false
    upgradeType: Replace
  platform:
    azure:
      diagnostics:
        storageAccountType: Managed
      encryptionAtHost: Enabled
      image:
        imageID: /subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourceGroups/ci-op-li75lz3r-eeed2-rg/providers/Microsoft.Compute/images/rhcos.x86_64.vhd
        type: ImageID
      osDisk:
        diskStorageAccountType: Premium_LRS
        sizeGiB: 120
      subnetID: /subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourceGroups/ci-op-li75lz3r-eeed2-vnet-rg/providers/Microsoft.Network/virtualNetworks/ci-op-li75lz3r-eeed2-vnet/subnets/ci-op-li75lz3r-eeed2-subnet
      vmSize: Standard_D4s_v3
    type: Azure
  release:
    image: registry.ci.openshift.org/ocp/release:4.19.0-0.nightly-2025-02-23-235415
  replicas: 1
status:
  replicas: 0
