apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: heli-test
  namespace: clusters
spec:
  config:
    - name: idms-cm
  arch: amd64
  clusterName: heli-test
  management:
    autoRepair: false
    upgradeType: Replace
  platform:
    aws:
      instanceProfile: heli-test-b5725-worker
      instanceType: m5.large
      rootVolume:
        size: 120
        type: gp3
      subnet:
        id: subnet-0a01184806e5d69b4
    type: AWS
  release:
    image: registry.ci.openshift.org/ocp/release:4.18.0-0.nightly-2025-01-15-030107
  replicas: 1
status:
  replicas: 0
